apiVersion: v1                      
kind: Namespace
metadata:
  name: app-253
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-253
  namespace: app-253
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - app-253
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: spoke1
  namespace: app-253
spec:
  clusters:
  - name: spoke1
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: test/github/multiresource
    apps.open-cluster-management.io/skip-hub-validation: 'true'
  labels:
    app: app-253
  name: app-253
  namespace: app-253
spec:
  channel: default/gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: spoke1
