apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: open-cluster-management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem