apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: mychannel
  namespace: secondsub
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  type: Git
  pathname: https://bitbucket.org/ekdjbdfh/othertest.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: second-level-sub
  namespace: secondsub
  annotations:
    apps.open-cluster-management.io/github-path: sub1
spec:
  channel: secondsub/mychannel
  placement:
    placementRef:
      name: dev-cluster
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-cluster
  namespace: secondsub
spec:
  clusterSelector:
    matchLabels:
      local-cluster: "true"
