
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-path: helmchart
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: testhelm
  name: testhelm-subscription-1
  namespace: default
spec:
  packageOverrides:
    - packageName: nginx
      packageAlias: nginx
      packageOverrides:
        - path: spec
          value:
            securityContext:
              runAsUser: "null"
              runAsGroup: "null"
  channel: ggithubcom-rokej-testrepo-ns/ggithubcom-rokej-testrepo
  placement:
    placementRef:
      kind: PlacementRule
      name: testhelm-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: testhelm
  name: testhelm-placement-1
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
