apiVersion: v1
kind: ConfigMap
metadata:
  name: perf-configmap-2
  namespace: multins
  annotations:
    test: "123"
  labels:
    test2: "abc"
data:
  path: resource44444
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
